### ISSUE TITLE
code issue

### ISSUE THREAD

**Issue by zakchary** [yeasy/pickleball_guide#1]
Hey, thank you so much. You did great by sharing this pickleball guide. i love pickleball too much as i am playing it for more than 2 years. i downloaded your provided code but it's not working on my side. the zip file is not opening on my side how to open it please help me.

**Comment by yeasy** [comment]
You can unpack the zip file using any zip tool such as 7-zip.
Or more simple, just download the pdf version from https://github.com/yeasy/pickleball_guide/releases/.
